# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.230.245:3306/verulia-db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: mysql_jxxMTY
    # HikariCP 连接池调优
    hikari:
      # 连接池名称
      pool-name: VeruliaHikariPool
      # 最小空闲连接数 (系统空闲时保留多少连接)
      minimum-idle: 10
      # 最大连接数 (并发上限，根据数据库服务器性能调整)
      maximum-pool-size: 50
      # 连接在池中的最大生命周期 (30分钟，避免数据库端主动断开导致报错)
      max-lifetime: 1800000
      # 连接超时时间 (30秒，拿不到连接就报错，防止线程卡死)
      connection-timeout: 30000
      # 空闲连接存活时间 (10分钟)
      idle-timeout: 600000

